name: Test React Code Workflow
on:
  push:
    paths:
      - 'project-02/**'
jobs:
  test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project-02
    steps:
      - name: Get Code (Checkout)
        uses: actions/checkout@v6-beta
      - name: Install NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
