name: Test React Code Workflow
on:
  push:
    paths:
      - 'Projects/Projects/02_ReactNodeJS/**'
jobs:
  test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/Projects/02_ReactNodeJS
    steps:
      - name: Get Code (Checkout)
        uses: actions/checkout@v6-beta
      - name: Install NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
